"""tour groups and departure rosters

Revision ID: 402b63427ea3
Revises: 6e2edf7da659
Create Date: 2026-09-03 00:17:49.560419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '402b63427ea3'
down_revision: Union[str, None] = '6e2edf7da659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Created explicitly for the same reason as the earlier migrations:
    # autogenerate renders the enum inline, which does not create the type.
    bind = op.get_bind()
    postgresql.ENUM('forming', 'confirmed', 'full', 'in_progress', 'completed', 'cancelled', name='tour_group_status').create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_groups',
    sa.Column('operator_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('destination', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('capacity', sa.Integer(), server_default='10', nullable=False),
    sa.Column('coordinator_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('forming', 'confirmed', 'full', 'in_progress', 'completed', 'cancelled', name='tour_group_status', create_type=False), server_default='forming', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity >= 1', name=op.f('ck_tour_groups_capacity_positive')),
    sa.CheckConstraint('length(btrim(name)) >= 2', name=op.f('ck_tour_groups_name_min_length')),
    sa.CheckConstraint('start_date <= end_date', name=op.f('ck_tour_groups_date_order')),
    sa.ForeignKeyConstraint(['coordinator_id'], ['operator_members.id'], name=op.f('fk_tour_groups_coordinator_id_operator_members'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], name=op.f('fk_tour_groups_operator_id_operators'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tour_groups'))
    )
    op.create_index('ix_tour_groups_operator_id', 'tour_groups', ['operator_id'], unique=False)
    op.create_index('ix_tour_groups_start_date', 'tour_groups', ['start_date'], unique=False)
    op.create_index('ix_tour_groups_status', 'tour_groups', ['status'], unique=False)
    op.create_table('tour_group_members',
    sa.Column('tour_group_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('traveller_id', sa.UUID(), nullable=False),
    sa.Column('seats', sa.Integer(), server_default='1', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('seats >= 1', name=op.f('ck_tour_group_members_seats_positive')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_tour_group_members_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tour_group_id'], ['tour_groups.id'], name=op.f('fk_tour_group_members_tour_group_id_tour_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['traveller_id'], ['users.id'], name=op.f('fk_tour_group_members_traveller_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tour_group_members')),
    sa.UniqueConstraint('tour_group_id', 'booking_id', name='uq_tour_group_members_tour_group_id_booking_id')
    )
    op.create_index('ix_tour_group_members_booking_id', 'tour_group_members', ['booking_id'], unique=False)
    op.create_index('ix_tour_group_members_tour_group_id', 'tour_group_members', ['tour_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tour_group_members_tour_group_id', table_name='tour_group_members')
    op.drop_index('ix_tour_group_members_booking_id', table_name='tour_group_members')
    op.drop_table('tour_group_members')
    op.drop_index('ix_tour_groups_status', table_name='tour_groups')
    op.drop_index('ix_tour_groups_start_date', table_name='tour_groups')
    op.drop_index('ix_tour_groups_operator_id', table_name='tour_groups')
    op.drop_table('tour_groups')
    # ### end Alembic commands ###

    postgresql.ENUM(name='tour_group_status').drop(bind, checkfirst=True)
