"""change requests and disruptions

Phase 5: dynamic tour management. Two tables and five enum types, plus three
new values on the existing ``notification_type``.

``ALTER TYPE ... ADD VALUE`` is safe inside a transaction on PostgreSQL 12+ so
long as the new value is not *used* in the same transaction, which nothing here
does. It cannot be undone -- PostgreSQL has no ``DROP VALUE`` -- so the
downgrade leaves the three notification values in place and says so rather than
pretending to reverse them.

Revision ID: 4ddeec285bba
Revises: 402b63427ea3
Create Date: 2026-09-03 12:25:37.078893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4ddeec285bba'
down_revision: Union[str, None] = '402b63427ea3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Created explicitly for the same reason as every earlier migration:
    # autogenerate renders the enum inline on the column, which does not
    # create the type, and the CREATE TABLE then fails on an unknown type.
    bind = op.get_bind()
    postgresql.ENUM(
        'weather', 'vendor_cancellation', 'transport_delay', 'closure',
        'safety', 'medical', 'other', name='disruption_type',
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        'low', 'medium', 'high', 'critical', name='disruption_severity',
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        'open', 'mitigating', 'resolved', 'dismissed', name='disruption_status',
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        'date_shift', 'replace_component', 'cancel_component',
        'add_component', 'party_size', name='change_request_type',
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        'pending', 'approved', 'countered', 'rejected', 'applied', 'withdrawn',
        name='change_request_status',
    ).create(bind, checkfirst=True)

    # Adaptation events on the existing notification type. IF NOT EXISTS makes
    # this re-runnable, which matters because the values cannot be removed on
    # downgrade and a re-upgrade would otherwise fail.
    for value in ('change_request', 'change_decision', 'disruption'):
        op.execute(
            f"ALTER TYPE notification_type ADD VALUE IF NOT EXISTS '{value}'"
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disruptions',
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('raised_by_id', sa.UUID(), nullable=True),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('type', postgresql.ENUM('weather', 'vendor_cancellation', 'transport_delay', 'closure', 'safety', 'medical', 'other', name='disruption_type', create_type=False), server_default='other', nullable=False),
    sa.Column('severity', postgresql.ENUM('low', 'medium', 'high', 'critical', name='disruption_severity', create_type=False), server_default='medium', nullable=False),
    sa.Column('status', postgresql.ENUM('open', 'mitigating', 'resolved', 'dismissed', name='disruption_status', create_type=False), server_default='open', nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('from_date IS NULL OR to_date IS NULL OR from_date <= to_date', name=op.f('ck_disruptions_date_order')),
    sa.CheckConstraint('length(btrim(title)) >= 3', name=op.f('ck_disruptions_title_min_length')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_disruptions_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], name=op.f('fk_disruptions_operator_id_operators'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raised_by_id'], ['users.id'], name=op.f('fk_disruptions_raised_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['vendor_services.id'], name=op.f('fk_disruptions_service_id_vendor_services'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_disruptions_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disruptions'))
    )
    op.create_index('ix_disruptions_booking_id', 'disruptions', ['booking_id'], unique=False)
    op.create_index('ix_disruptions_from_date', 'disruptions', ['from_date'], unique=False)
    op.create_index('ix_disruptions_operator_id', 'disruptions', ['operator_id'], unique=False)
    op.create_index('ix_disruptions_status', 'disruptions', ['status'], unique=False)
    op.create_index('ix_disruptions_trip_id', 'disruptions', ['trip_id'], unique=False)
    op.create_table('change_requests',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('booking_item_id', sa.UUID(), nullable=True),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('disruption_id', sa.UUID(), nullable=True),
    sa.Column('requested_by_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('type', postgresql.ENUM('date_shift', 'replace_component', 'cancel_component', 'add_component', 'party_size', name='change_request_type', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'countered', 'rejected', 'applied', 'withdrawn', name='change_request_status', create_type=False), server_default='pending', nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('proposal', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('impact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('net_cost_delta', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status IN ('pending', 'withdrawn')) = (decided_at IS NULL)", name=op.f('ck_change_requests_decided_at_matches_status')),
    sa.CheckConstraint("applied_at IS NULL OR status = 'applied'", name=op.f('ck_change_requests_applied_at_requires_applied')),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_change_requests_currency_iso4217')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_change_requests_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['booking_item_id'], ['booking_items.id'], name=op.f('fk_change_requests_booking_item_id_booking_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['disruption_id'], ['disruptions.id'], name=op.f('fk_change_requests_disruption_id_disruptions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], name=op.f('fk_change_requests_operator_id_operators'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_change_requests_requested_by_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['operator_members.id'], name=op.f('fk_change_requests_reviewed_by_id_operator_members'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_change_requests_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_change_requests'))
    )
    op.create_index('ix_change_requests_booking_id', 'change_requests', ['booking_id'], unique=False)
    op.create_index('ix_change_requests_created_at', 'change_requests', ['created_at'], unique=False)
    op.create_index('ix_change_requests_disruption_id', 'change_requests', ['disruption_id'], unique=False)
    op.create_index('ix_change_requests_operator_id', 'change_requests', ['operator_id'], unique=False)
    op.create_index('ix_change_requests_status', 'change_requests', ['status'], unique=False)
    op.create_index('ix_change_requests_trip_id', 'change_requests', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_change_requests_trip_id', table_name='change_requests')
    op.drop_index('ix_change_requests_status', table_name='change_requests')
    op.drop_index('ix_change_requests_operator_id', table_name='change_requests')
    op.drop_index('ix_change_requests_disruption_id', table_name='change_requests')
    op.drop_index('ix_change_requests_created_at', table_name='change_requests')
    op.drop_index('ix_change_requests_booking_id', table_name='change_requests')
    op.drop_table('change_requests')
    op.drop_index('ix_disruptions_trip_id', table_name='disruptions')
    op.drop_index('ix_disruptions_status', table_name='disruptions')
    op.drop_index('ix_disruptions_operator_id', table_name='disruptions')
    op.drop_index('ix_disruptions_from_date', table_name='disruptions')
    op.drop_index('ix_disruptions_booking_id', table_name='disruptions')
    op.drop_table('disruptions')
    # ### end Alembic commands ###

    bind = op.get_bind()
    for name in (
        'change_request_status',
        'change_request_type',
        'disruption_status',
        'disruption_severity',
        'disruption_type',
    ):
        postgresql.ENUM(name=name).drop(bind, checkfirst=True)

    # The three notification_type values stay: PostgreSQL cannot drop an enum
    # value, and recreating the type would mean rewriting every column that
    # uses it. They are inert without the tables above.
