"""personalisation preferences, operators, vendors and bookable inventory

Revision ID: 6bba515031c9
Revises: af7f1d4418b2
Create Date: 2026-09-02 22:24:01.180411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6bba515031c9'
down_revision: Union[str, None] = 'af7f1d4418b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create every new enum type up front, explicitly.
    #
    # Autogenerate renders enums inline on each column, which does not work
    # here for two reasons: `add_column` never emits CREATE TYPE, so
    # `travel_style` and `travel_pace` would not exist when user_preferences
    # is altered; and `service_type` and `comfort_tier` are each used by more
    # than one table, so the implicit create would run twice and fail with
    # "type already exists". Creating them here with checkfirst, and
    # rendering every reference below with create_type=False, removes both
    # failure modes and the ordering dependency between them.
    bind = op.get_bind()
    postgresql.ENUM('owner', 'manager', 'coordinator', name='operator_role').create(bind, checkfirst=True)
    postgresql.ENUM('accommodation', 'transport', 'activity', 'guide', 'meal', 'other', name='service_type').create(bind, checkfirst=True)
    postgresql.ENUM('budget', 'standard', 'premium', 'luxury', name='comfort_tier').create(bind, checkfirst=True)
    postgresql.ENUM('solo', 'couple', 'family', 'friends', 'business', 'backpacking', 'luxury', name='travel_style').create(bind, checkfirst=True)
    postgresql.ENUM('relaxed', 'balanced', 'packed', name='travel_pace').create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operators',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(btrim(name)) >= 2', name=op.f('ck_operators_name_min_length')),
    sa.CheckConstraint('rating IS NULL OR (rating BETWEEN 0 AND 5)', name=op.f('ck_operators_rating_range')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operators')),
    sa.UniqueConstraint('slug', name=op.f('uq_operators_slug'))
    )
    op.create_index('ix_operators_slug', 'operators', ['slug'], unique=False)
    op.create_table('operator_members',
    sa.Column('operator_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', postgresql.ENUM('owner', 'manager', 'coordinator', name='operator_role', create_type=False), server_default='coordinator', nullable=False),
    sa.Column('job_title', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], name=op.f('fk_operator_members_operator_id_operators'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_operator_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operator_members')),
    sa.UniqueConstraint('operator_id', 'user_id', name='uq_operator_members_operator_id_user_id')
    )
    op.create_index('ix_operator_members_operator_id', 'operator_members', ['operator_id'], unique=False)
    op.create_index('ix_operator_members_user_id', 'operator_members', ['user_id'], unique=False)
    op.create_table('vendors',
    sa.Column('operator_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', postgresql.ENUM('accommodation', 'transport', 'activity', 'guide', 'meal', 'other', name='service_type', create_type=False), server_default='other', nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('reliability_score', sa.Integer(), server_default='80', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(btrim(name)) >= 2', name=op.f('ck_vendors_name_min_length')),
    sa.CheckConstraint('rating IS NULL OR (rating BETWEEN 0 AND 5)', name=op.f('ck_vendors_rating_range')),
    sa.CheckConstraint('reliability_score BETWEEN 0 AND 100', name=op.f('ck_vendors_reliability_range')),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], name=op.f('fk_vendors_operator_id_operators'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendors'))
    )
    op.create_index('ix_vendors_category', 'vendors', ['category'], unique=False)
    op.create_index('ix_vendors_city', 'vendors', ['city'], unique=False)
    op.create_index('ix_vendors_operator_id', 'vendors', ['operator_id'], unique=False)
    op.create_table('vendor_services',
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('service_type', postgresql.ENUM('accommodation', 'transport', 'activity', 'guide', 'meal', 'other', name='service_type', create_type=False), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('comfort_tier', postgresql.ENUM('budget', 'standard', 'premium', 'luxury', name='comfort_tier', create_type=False), server_default='standard', nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('unit_label', sa.String(length=30), server_default='unit', nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('free_cancellation_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cancellation_penalty_pct', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_vendor_services_currency_iso4217')),
    sa.CheckConstraint('cancellation_penalty_pct BETWEEN 0 AND 100', name=op.f('ck_vendor_services_cancellation_penalty_range')),
    sa.CheckConstraint('duration_minutes IS NULL OR duration_minutes > 0', name=op.f('ck_vendor_services_duration_positive')),
    sa.CheckConstraint('free_cancellation_days >= 0', name=op.f('ck_vendor_services_free_cancellation_days_non_negative')),
    sa.CheckConstraint('length(btrim(name)) >= 2', name=op.f('ck_vendor_services_name_min_length')),
    sa.CheckConstraint('rating IS NULL OR (rating BETWEEN 0 AND 5)', name=op.f('ck_vendor_services_rating_range')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_vendor_services_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_vendor_services_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vendor_services'))
    )
    op.create_index('ix_vendor_services_city', 'vendor_services', ['city'], unique=False)
    op.create_index('ix_vendor_services_comfort_tier', 'vendor_services', ['comfort_tier'], unique=False)
    op.create_index('ix_vendor_services_service_type', 'vendor_services', ['service_type'], unique=False)
    op.create_index('ix_vendor_services_vendor_id', 'vendor_services', ['vendor_id'], unique=False)
    op.create_table('service_availability',
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('on_date', sa.Date(), nullable=False),
    sa.Column('capacity_total', sa.Integer(), server_default='0', nullable=False),
    sa.Column('capacity_booked', sa.Integer(), server_default='0', nullable=False),
    sa.Column('price_override', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity_booked <= capacity_total', name=op.f('ck_service_availability_not_overbooked')),
    sa.CheckConstraint('capacity_booked >= 0', name=op.f('ck_service_availability_capacity_booked_non_negative')),
    sa.CheckConstraint('capacity_total >= 0', name=op.f('ck_service_availability_capacity_total_non_negative')),
    sa.CheckConstraint('price_override IS NULL OR price_override >= 0', name=op.f('ck_service_availability_price_override_non_negative')),
    sa.ForeignKeyConstraint(['service_id'], ['vendor_services.id'], name=op.f('fk_service_availability_service_id_vendor_services'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_availability')),
    sa.UniqueConstraint('service_id', 'on_date', name='uq_service_availability_service_id_on_date')
    )
    op.create_index('ix_service_availability_on_date', 'service_availability', ['on_date'], unique=False)
    op.create_index('ix_service_availability_service_id', 'service_availability', ['service_id'], unique=False)
    op.add_column('user_preferences', sa.Column('travel_style', postgresql.ENUM('solo', 'couple', 'family', 'friends', 'business', 'backpacking', 'luxury', name='travel_style', create_type=False), nullable=True))
    op.add_column('user_preferences', sa.Column('pace', postgresql.ENUM('relaxed', 'balanced', 'packed', name='travel_pace', create_type=False), nullable=True))
    op.add_column('user_preferences', sa.Column('accommodation_class', postgresql.ENUM('budget', 'standard', 'premium', 'luxury', name='comfort_tier', create_type=False), nullable=True))
    op.add_column('user_preferences', sa.Column('transport_class', postgresql.ENUM('budget', 'standard', 'premium', 'luxury', name='comfort_tier', create_type=False), nullable=True))
    op.add_column('user_preferences', sa.Column('preferred_transport_modes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('user_preferences', sa.Column('interests', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('user_preferences', sa.Column('dietary_requirements', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('user_preferences', sa.Column('mobility_needs', sa.Text(), nullable=True))
    op.add_column('user_preferences', sa.Column('daily_budget_cap', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'daily_budget_cap')
    op.drop_column('user_preferences', 'mobility_needs')
    op.drop_column('user_preferences', 'dietary_requirements')
    op.drop_column('user_preferences', 'interests')
    op.drop_column('user_preferences', 'preferred_transport_modes')
    op.drop_column('user_preferences', 'transport_class')
    op.drop_column('user_preferences', 'accommodation_class')
    op.drop_column('user_preferences', 'pace')
    op.drop_column('user_preferences', 'travel_style')
    op.drop_index('ix_service_availability_service_id', table_name='service_availability')
    op.drop_index('ix_service_availability_on_date', table_name='service_availability')
    op.drop_table('service_availability')
    op.drop_index('ix_vendor_services_vendor_id', table_name='vendor_services')
    op.drop_index('ix_vendor_services_service_type', table_name='vendor_services')
    op.drop_index('ix_vendor_services_comfort_tier', table_name='vendor_services')
    op.drop_index('ix_vendor_services_city', table_name='vendor_services')
    op.drop_table('vendor_services')
    op.drop_index('ix_vendors_operator_id', table_name='vendors')
    op.drop_index('ix_vendors_city', table_name='vendors')
    op.drop_index('ix_vendors_category', table_name='vendors')
    op.drop_table('vendors')
    op.drop_index('ix_operator_members_user_id', table_name='operator_members')
    op.drop_index('ix_operator_members_operator_id', table_name='operator_members')
    op.drop_table('operator_members')
    op.drop_index('ix_operators_slug', table_name='operators')
    op.drop_table('operators')
    # ### end Alembic commands ###

    # Types last: dropping one still referenced by a column would fail.
    postgresql.ENUM(name='travel_pace').drop(bind, checkfirst=True)
    postgresql.ENUM(name='travel_style').drop(bind, checkfirst=True)
    postgresql.ENUM(name='comfort_tier').drop(bind, checkfirst=True)
    postgresql.ENUM(name='service_type').drop(bind, checkfirst=True)
    postgresql.ENUM(name='operator_role').drop(bind, checkfirst=True)
