"""bookings, booking items and payments

Revision ID: 6e2edf7da659
Revises: 6bba515031c9
Create Date: 2026-09-02 23:49:55.709567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6e2edf7da659'
down_revision: Union[str, None] = '6bba515031c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enum types created explicitly, for the same reasons as the previous
    # migration: `add_column` never emits CREATE TYPE, and a type shared by
    # more than one table would otherwise be created twice. `service_type`
    # already exists from revision 6bba515031c9 and is referenced below with
    # create_type=False so nothing tries to redefine it.
    bind = op.get_bind()
    postgresql.ENUM('draft', 'pending_payment', 'confirmed', 'in_progress', 'completed', 'cancelled', name='booking_status').create(bind, checkfirst=True)
    postgresql.ENUM('pending', 'confirmed', 'cancelled', 'replaced', name='booking_item_status').create(bind, checkfirst=True)
    postgresql.ENUM('deposit', 'instalment', 'full', 'refund', name='payment_kind').create(bind, checkfirst=True)
    postgresql.ENUM('initiated', 'authorized', 'captured', 'failed', 'refunded', name='payment_status').create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('traveller_id', sa.UUID(), nullable=False),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('reference', sa.String(length=16), nullable=False),
    sa.Column('status', postgresql.ENUM('draft', 'pending_payment', 'confirmed', 'in_progress', 'completed', 'cancelled', name='booking_status', create_type=False), server_default='draft', nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_bookings_currency_iso4217')),
    sa.CheckConstraint('discount >= 0', name=op.f('ck_bookings_discount_non_negative')),
    sa.CheckConstraint('subtotal >= 0', name=op.f('ck_bookings_subtotal_non_negative')),
    sa.CheckConstraint('tax >= 0', name=op.f('ck_bookings_tax_non_negative')),
    sa.CheckConstraint('total >= 0', name=op.f('ck_bookings_total_non_negative')),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], name=op.f('fk_bookings_operator_id_operators'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['traveller_id'], ['users.id'], name=op.f('fk_bookings_traveller_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_bookings_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings')),
    sa.UniqueConstraint('reference', name=op.f('uq_bookings_reference'))
    )
    op.create_index('ix_bookings_operator_id', 'bookings', ['operator_id'], unique=False)
    op.create_index('ix_bookings_reference', 'bookings', ['reference'], unique=False)
    op.create_index('ix_bookings_status', 'bookings', ['status'], unique=False)
    op.create_index('ix_bookings_traveller_id', 'bookings', ['traveller_id'], unique=False)
    op.create_index('ix_bookings_trip_id', 'bookings', ['trip_id'], unique=False)
    op.create_table('payments',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('kind', postgresql.ENUM('deposit', 'instalment', 'full', 'refund', name='payment_kind', create_type=False), server_default='full', nullable=False),
    sa.Column('status', postgresql.ENUM('initiated', 'authorized', 'captured', 'failed', 'refunded', name='payment_status', create_type=False), server_default='initiated', nullable=False),
    sa.Column('method', sa.String(length=40), nullable=True),
    sa.Column('gateway_reference', sa.String(length=64), nullable=True),
    sa.Column('failure_reason', sa.String(length=200), nullable=True),
    sa.Column('refund_of_payment_id', sa.UUID(), nullable=True),
    sa.Column('authorized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_payments_currency_iso4217')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payments_amount_positive')),
    sa.CheckConstraint('refund_of_payment_id IS NULL OR refund_of_payment_id <> id', name=op.f('ck_payments_no_self_refund')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_payments_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['refund_of_payment_id'], ['payments.id'], name=op.f('fk_payments_refund_of_payment_id_payments'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    op.create_index('ix_payments_booking_id', 'payments', ['booking_id'], unique=False)
    op.create_index('ix_payments_created_at', 'payments', ['created_at'], unique=False)
    op.create_index('ix_payments_status', 'payments', ['status'], unique=False)
    op.create_table('booking_items',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('stop_id', sa.UUID(), nullable=True),
    sa.Column('itinerary_activity_id', sa.UUID(), nullable=True),
    sa.Column('component_type', postgresql.ENUM('accommodation', 'transport', 'activity', 'guide', 'meal', 'other', name='service_type', create_type=False), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('vendor_name', sa.String(length=160), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('units', sa.Integer(), server_default='1', nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('free_cancellation_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cancellation_penalty_pct', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'confirmed', 'cancelled', 'replaced', name='booking_item_status', create_type=False), server_default='pending', nullable=False),
    sa.Column('replaced_by_item_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cancellation_penalty_pct BETWEEN 0 AND 100', name=op.f('ck_booking_items_cancellation_penalty_range')),
    sa.CheckConstraint('end_date IS NULL OR end_date >= service_date', name=op.f('ck_booking_items_date_order')),
    sa.CheckConstraint('quantity >= 1', name=op.f('ck_booking_items_quantity_positive')),
    sa.CheckConstraint('replaced_by_item_id IS NULL OR replaced_by_item_id <> id', name=op.f('ck_booking_items_no_self_replacement')),
    sa.CheckConstraint('total_price >= 0', name=op.f('ck_booking_items_total_price_non_negative')),
    sa.CheckConstraint('unit_price >= 0', name=op.f('ck_booking_items_unit_price_non_negative')),
    sa.CheckConstraint('units >= 1', name=op.f('ck_booking_items_units_positive')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_booking_items_booking_id_bookings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['itinerary_activity_id'], ['itinerary_activities.id'], name=op.f('fk_booking_items_itinerary_activity_id_itinerary_activities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['replaced_by_item_id'], ['booking_items.id'], name=op.f('fk_booking_items_replaced_by_item_id_booking_items'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['vendor_services.id'], name=op.f('fk_booking_items_service_id_vendor_services'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stop_id'], ['trip_stops.id'], name=op.f('fk_booking_items_stop_id_trip_stops'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_booking_items'))
    )
    op.create_index('ix_booking_items_booking_id', 'booking_items', ['booking_id'], unique=False)
    op.create_index('ix_booking_items_service_date', 'booking_items', ['service_date'], unique=False)
    op.create_index('ix_booking_items_service_id', 'booking_items', ['service_id'], unique=False)
    op.create_index('ix_booking_items_status', 'booking_items', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_booking_items_status', table_name='booking_items')
    op.drop_index('ix_booking_items_service_id', table_name='booking_items')
    op.drop_index('ix_booking_items_service_date', table_name='booking_items')
    op.drop_index('ix_booking_items_booking_id', table_name='booking_items')
    op.drop_table('booking_items')
    op.drop_index('ix_payments_status', table_name='payments')
    op.drop_index('ix_payments_created_at', table_name='payments')
    op.drop_index('ix_payments_booking_id', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_bookings_trip_id', table_name='bookings')
    op.drop_index('ix_bookings_traveller_id', table_name='bookings')
    op.drop_index('ix_bookings_status', table_name='bookings')
    op.drop_index('ix_bookings_reference', table_name='bookings')
    op.drop_index('ix_bookings_operator_id', table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###

    # Types last: dropping one still referenced by a column would fail.
    postgresql.ENUM(name='payment_status').drop(bind, checkfirst=True)
    postgresql.ENUM(name='payment_kind').drop(bind, checkfirst=True)
    postgresql.ENUM(name='booking_item_status').drop(bind, checkfirst=True)
    postgresql.ENUM(name='booking_status').drop(bind, checkfirst=True)
