"""initial schema

Revision ID: 8c0fc53b800b
Revises: 
Create Date: 2026-08-22 10:16:37.976893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8c0fc53b800b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destinations',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost_index', sa.Integer(), server_default='3', nullable=False),
    sa.Column('popularity_score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cost_index BETWEEN 1 AND 5', name=op.f('ck_destinations_cost_index_range')),
    sa.CheckConstraint('latitude IS NULL OR (latitude BETWEEN -90 AND 90)', name=op.f('ck_destinations_latitude_range')),
    sa.CheckConstraint('length(btrim(country)) > 0', name=op.f('ck_destinations_country_not_blank')),
    sa.CheckConstraint('length(btrim(name)) > 0', name=op.f('ck_destinations_name_not_blank')),
    sa.CheckConstraint('longitude IS NULL OR (longitude BETWEEN -180 AND 180)', name=op.f('ck_destinations_longitude_range')),
    sa.CheckConstraint('popularity_score >= 0', name=op.f('ck_destinations_popularity_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_destinations'))
    )
    op.create_index('ix_destinations_country', 'destinations', ['country'], unique=False)
    op.create_index('ix_destinations_popularity', 'destinations', ['popularity_score'], unique=False)
    op.create_index('ix_destinations_region', 'destinations', ['region'], unique=False)
    op.create_index('uq_destinations_name_country', 'destinations', [sa.text('lower(name)'), sa.text('lower(country)')], unique=True)
    op.create_table('users',
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('additional_info', sa.Text(), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role'), server_default='user', nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'deleted', name='user_status'), server_default='active', nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("position('@' in email) > 1", name=op.f('ck_users_email_has_at')),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_users_email_lowercase')),
    sa.CheckConstraint('length(btrim(first_name)) > 0', name=op.f('ck_users_first_name_not_blank')),
    sa.CheckConstraint('length(btrim(last_name)) > 0', name=op.f('ck_users_last_name_not_blank')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index('ix_users_email_lower', 'users', [sa.text('lower(email)')], unique=True)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index('ix_users_status', 'users', ['status'], unique=False)
    op.create_table('activities',
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('adventure', 'sightseeing', 'food', 'culture', 'nature', 'nightlife', 'shopping', 'relaxation', 'other', name='activity_category'), server_default='other', nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.Numeric(precision=2, scale=1), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_activities_currency_iso4217')),
    sa.CheckConstraint('duration_minutes IS NULL OR duration_minutes > 0', name=op.f('ck_activities_duration_positive')),
    sa.CheckConstraint('estimated_cost >= 0', name=op.f('ck_activities_estimated_cost_non_negative')),
    sa.CheckConstraint('length(btrim(title)) > 0', name=op.f('ck_activities_title_not_blank')),
    sa.CheckConstraint('rating IS NULL OR (rating BETWEEN 0 AND 5)', name=op.f('ck_activities_rating_range')),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], name=op.f('fk_activities_destination_id_destinations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activities'))
    )
    op.create_index('ix_activities_category', 'activities', ['category'], unique=False)
    op.create_index('ix_activities_cost', 'activities', ['estimated_cost'], unique=False)
    op.create_index('ix_activities_destination_id', 'activities', ['destination_id'], unique=False)
    op.create_table('email_verification_codes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempts >= 0', name=op.f('ck_email_verification_codes_attempts_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_email_verification_codes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_verification_codes'))
    )
    op.create_index('ix_email_verification_codes_email', 'email_verification_codes', ['email'], unique=False)
    op.create_index('ix_email_verification_codes_expires_at', 'email_verification_codes', ['expires_at'], unique=False)
    op.create_index('ix_email_verification_codes_user_id', 'email_verification_codes', ['user_id'], unique=False)
    op.create_table('revoked_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_revoked_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_revoked_tokens')),
    sa.UniqueConstraint('jti', name=op.f('uq_revoked_tokens_jti'))
    )
    op.create_index('ix_revoked_tokens_expires_at', 'revoked_tokens', ['expires_at'], unique=False)
    op.create_index('ix_revoked_tokens_jti', 'revoked_tokens', ['jti'], unique=False)
    op.create_table('saved_destinations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], name=op.f('fk_saved_destinations_destination_id_destinations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_destinations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'destination_id', name=op.f('pk_saved_destinations'))
    )
    op.create_table('trips',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('traveller_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('draft', 'upcoming', 'ongoing', 'completed', name='trip_status'), server_default='draft', nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('share_slug', sa.String(length=64), nullable=True),
    sa.Column('cloned_from_trip_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_trips_currency_iso4217')),
    sa.CheckConstraint('(is_public = false AND share_slug IS NULL) OR (is_public = true AND share_slug IS NOT NULL)', name=op.f('ck_trips_public_requires_slug')),
    sa.CheckConstraint('budget >= 0', name=op.f('ck_trips_budget_non_negative')),
    sa.CheckConstraint('cloned_from_trip_id IS NULL OR cloned_from_trip_id <> id', name=op.f('ck_trips_no_self_clone')),
    sa.CheckConstraint('length(btrim(title)) >= 3', name=op.f('ck_trips_title_min_length')),
    sa.CheckConstraint('start_date <= end_date', name=op.f('ck_trips_date_order')),
    sa.CheckConstraint('traveller_count <= 50', name=op.f('ck_trips_traveller_count_max')),
    sa.CheckConstraint('traveller_count >= 1', name=op.f('ck_trips_traveller_count_positive')),
    sa.ForeignKeyConstraint(['cloned_from_trip_id'], ['trips.id'], name=op.f('fk_trips_cloned_from_trip_id_trips'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_trips_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trips')),
    sa.UniqueConstraint('share_slug', name=op.f('uq_trips_share_slug'))
    )
    op.create_index('ix_trips_deleted_at', 'trips', ['deleted_at'], unique=False)
    op.create_index('ix_trips_share_slug', 'trips', ['share_slug'], unique=False)
    op.create_index('ix_trips_start_date', 'trips', ['start_date'], unique=False)
    op.create_index('ix_trips_status', 'trips', ['status'], unique=False)
    op.create_index('ix_trips_user_id', 'trips', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('default_traveller_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('preferred_categories', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('home_city', sa.String(length=100), nullable=True),
    sa.Column('home_country', sa.String(length=100), nullable=True),
    sa.Column('email_notifications', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f('ck_user_preferences_currency_iso4217')),
    sa.CheckConstraint('default_traveller_count >= 1', name=op.f('ck_user_preferences_default_traveller_count_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_preferences')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_preferences_user_id'))
    )
    op.create_table('trip_stops',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=True),
    sa.Column('city_name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('arrival_date <= departure_date', name=op.f('ck_trip_stops_date_order')),
    sa.CheckConstraint('length(btrim(city_name)) >= 2', name=op.f('ck_trip_stops_city_name_min_length')),
    sa.CheckConstraint('order_index >= 0', name=op.f('ck_trip_stops_order_index_non_negative')),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], name=op.f('fk_trip_stops_destination_id_destinations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_trip_stops_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_stops')),
    sa.UniqueConstraint('trip_id', 'order_index', deferrable='True', initially='DEFERRED', name='uq_trip_stops_trip_id_order_index')
    )
    op.create_index('ix_trip_stops_destination_id', 'trip_stops', ['destination_id'], unique=False)
    op.create_index('ix_trip_stops_trip_id', 'trip_stops', ['trip_id'], unique=False)
    op.create_table('accommodations',
    sa.Column('stop_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('booking_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('check_in <= check_out', name=op.f('ck_accommodations_date_order')),
    sa.CheckConstraint('estimated_cost >= 0', name=op.f('ck_accommodations_estimated_cost_non_negative')),
    sa.CheckConstraint('length(btrim(name)) >= 2', name=op.f('ck_accommodations_name_min_length')),
    sa.ForeignKeyConstraint(['stop_id'], ['trip_stops.id'], name=op.f('fk_accommodations_stop_id_trip_stops'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accommodations'))
    )
    op.create_index('ix_accommodations_stop_id', 'accommodations', ['stop_id'], unique=False)
    op.create_table('expenses',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('stop_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.Enum('transport', 'accommodation', 'activities', 'meals', 'miscellaneous', name='expense_category'), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expense_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_expenses_amount_positive')),
    sa.CheckConstraint('length(btrim(title)) >= 2', name=op.f('ck_expenses_title_min_length')),
    sa.ForeignKeyConstraint(['stop_id'], ['trip_stops.id'], name=op.f('fk_expenses_stop_id_trip_stops'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_expenses_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_index('ix_expenses_category', 'expenses', ['category'], unique=False)
    op.create_index('ix_expenses_expense_date', 'expenses', ['expense_date'], unique=False)
    op.create_index('ix_expenses_trip_id', 'expenses', ['trip_id'], unique=False)
    op.create_table('itinerary_activities',
    sa.Column('stop_id', sa.UUID(), nullable=False),
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('category', sa.Enum('adventure', 'sightseeing', 'food', 'culture', 'nature', 'nightlife', 'shopping', 'relaxation', 'other', name='activity_category'), server_default='other', nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_time IS NULL OR start_time IS NOT NULL', name=op.f('ck_itinerary_activities_end_time_requires_start_time')),
    sa.CheckConstraint('estimated_cost >= 0', name=op.f('ck_itinerary_activities_estimated_cost_non_negative')),
    sa.CheckConstraint('length(btrim(title)) >= 2', name=op.f('ck_itinerary_activities_title_min_length')),
    sa.CheckConstraint('order_index >= 0', name=op.f('ck_itinerary_activities_order_index_non_negative')),
    sa.CheckConstraint('start_time IS NULL OR end_time IS NULL OR start_time < end_time', name=op.f('ck_itinerary_activities_time_order')),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_itinerary_activities_activity_id_activities'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stop_id'], ['trip_stops.id'], name=op.f('fk_itinerary_activities_stop_id_trip_stops'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_itinerary_activities')),
    sa.UniqueConstraint('stop_id', 'order_index', deferrable='True', initially='DEFERRED', name='uq_itinerary_activities_stop_id_order_index')
    )
    op.create_index('ix_itinerary_activities_activity_date', 'itinerary_activities', ['activity_date'], unique=False)
    op.create_index('ix_itinerary_activities_stop_id', 'itinerary_activities', ['stop_id'], unique=False)
    op.create_table('transport',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('origin_stop_id', sa.UUID(), nullable=True),
    sa.Column('destination_stop_id', sa.UUID(), nullable=True),
    sa.Column('transport_type', sa.Enum('flight', 'train', 'bus', 'car', 'ferry', 'other', name='transport_type'), server_default='other', nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('departure_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrival_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('booking_ref', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cost >= 0', name=op.f('ck_transport_cost_non_negative')),
    sa.CheckConstraint('departure_time < arrival_time', name=op.f('ck_transport_time_order')),
    sa.CheckConstraint('origin_stop_id IS NULL OR destination_stop_id IS NULL OR origin_stop_id <> destination_stop_id', name=op.f('ck_transport_distinct_stops')),
    sa.ForeignKeyConstraint(['destination_stop_id'], ['trip_stops.id'], name=op.f('fk_transport_destination_stop_id_trip_stops'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['origin_stop_id'], ['trip_stops.id'], name=op.f('fk_transport_origin_stop_id_trip_stops'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_transport_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transport'))
    )
    op.create_index('ix_transport_departure_time', 'transport', ['departure_time'], unique=False)
    op.create_index('ix_transport_trip_id', 'transport', ['trip_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transport_trip_id', table_name='transport')
    op.drop_index('ix_transport_departure_time', table_name='transport')
    op.drop_table('transport')
    op.drop_index('ix_itinerary_activities_stop_id', table_name='itinerary_activities')
    op.drop_index('ix_itinerary_activities_activity_date', table_name='itinerary_activities')
    op.drop_table('itinerary_activities')
    op.drop_index('ix_expenses_trip_id', table_name='expenses')
    op.drop_index('ix_expenses_expense_date', table_name='expenses')
    op.drop_index('ix_expenses_category', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('ix_accommodations_stop_id', table_name='accommodations')
    op.drop_table('accommodations')
    op.drop_index('ix_trip_stops_trip_id', table_name='trip_stops')
    op.drop_index('ix_trip_stops_destination_id', table_name='trip_stops')
    op.drop_table('trip_stops')
    op.drop_table('user_preferences')
    op.drop_index('ix_trips_user_id', table_name='trips')
    op.drop_index('ix_trips_status', table_name='trips')
    op.drop_index('ix_trips_start_date', table_name='trips')
    op.drop_index('ix_trips_share_slug', table_name='trips')
    op.drop_index('ix_trips_deleted_at', table_name='trips')
    op.drop_table('trips')
    op.drop_table('saved_destinations')
    op.drop_index('ix_revoked_tokens_jti', table_name='revoked_tokens')
    op.drop_index('ix_revoked_tokens_expires_at', table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_index('ix_email_verification_codes_user_id', table_name='email_verification_codes')
    op.drop_index('ix_email_verification_codes_expires_at', table_name='email_verification_codes')
    op.drop_index('ix_email_verification_codes_email', table_name='email_verification_codes')
    op.drop_table('email_verification_codes')
    op.drop_index('ix_activities_destination_id', table_name='activities')
    op.drop_index('ix_activities_cost', table_name='activities')
    op.drop_index('ix_activities_category', table_name='activities')
    op.drop_table('activities')
    op.drop_index('ix_users_status', table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_email_lower', table_name='users')
    op.drop_table('users')
    op.drop_index('uq_destinations_name_country', table_name='destinations')
    op.drop_index('ix_destinations_region', table_name='destinations')
    op.drop_index('ix_destinations_popularity', table_name='destinations')
    op.drop_index('ix_destinations_country', table_name='destinations')
    op.drop_table('destinations')
    # ### end Alembic commands ###
