"""assist threads and reviews

Phase 6. Three tables and three enum types, plus two new values on the
existing ``notification_type``.

As in every earlier migration the enum types are created explicitly:
autogenerate renders the enum inline on the column, which does not create the
type, and the CREATE TABLE then fails on an unknown type. The two
notification values cannot be removed on downgrade -- PostgreSQL has no
``DROP VALUE`` -- so the downgrade leaves them and says so rather than
pretending to reverse them.

Revision ID: ac7375836db9
Revises: 4ddeec285bba

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ac7375836db9'
down_revision: Union[str, None] = '4ddeec285bba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    postgresql.ENUM(
        'open', 'waiting', 'resolved', 'closed', name='assist_thread_status',
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        'traveller', 'coordinator', 'ai', name='assist_sender',
    ).create(bind, checkfirst=True)
    postgresql.ENUM(
        'trip', 'vendor', 'service', 'operator', name='review_subject',
    ).create(bind, checkfirst=True)

    for value in ('assist_reply', 'review_request'):
        op.execute(
            f"ALTER TYPE notification_type ADD VALUE IF NOT EXISTS '{value}'"
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assist_threads',
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('traveller_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('assigned_member_id', sa.UUID(), nullable=True),
    sa.Column('subject', sa.String(length=160), nullable=False),
    sa.Column('status', postgresql.ENUM('open', 'waiting', 'resolved', 'closed', name='assist_thread_status', create_type=False), server_default='open', nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(btrim(subject)) >= 3', name=op.f('ck_assist_threads_subject_min_length')),
    sa.ForeignKeyConstraint(['assigned_member_id'], ['operator_members.id'], name=op.f('fk_assist_threads_assigned_member_id_operator_members'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_assist_threads_booking_id_bookings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], name=op.f('fk_assist_threads_operator_id_operators'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['traveller_id'], ['users.id'], name=op.f('fk_assist_threads_traveller_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_assist_threads_trip_id_trips'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assist_threads'))
    )
    op.create_index('ix_assist_threads_last_message_at', 'assist_threads', ['last_message_at'], unique=False)
    op.create_index('ix_assist_threads_operator_id', 'assist_threads', ['operator_id'], unique=False)
    op.create_index('ix_assist_threads_status', 'assist_threads', ['status'], unique=False)
    op.create_index('ix_assist_threads_traveller_id', 'assist_threads', ['traveller_id'], unique=False)
    op.create_index('ix_assist_threads_trip_id', 'assist_threads', ['trip_id'], unique=False)
    op.create_table('reviews',
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('subject', postgresql.ENUM('trip', 'vendor', 'service', 'operator', name='review_subject', create_type=False), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('vendor_id', sa.UUID(), nullable=True),
    sa.Column('service_id', sa.UUID(), nullable=True),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_public', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(subject = 'trip' AND trip_id IS NOT NULL) OR (subject = 'vendor' AND vendor_id IS NOT NULL) OR (subject = 'service' AND service_id IS NOT NULL) OR (subject = 'operator' AND operator_id IS NOT NULL)", name=op.f('ck_reviews_subject_matches_target')),
    sa.CheckConstraint('(CASE WHEN trip_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN vendor_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN service_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN operator_id IS NOT NULL THEN 1 ELSE 0 END) = 1', name=op.f('ck_reviews_exactly_one_subject')),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_reviews_rating_range')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_reviews_author_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_reviews_booking_id_bookings'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], name=op.f('fk_reviews_operator_id_operators'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['vendor_services.id'], name=op.f('fk_reviews_service_id_vendor_services'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_reviews_trip_id_trips'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], name=op.f('fk_reviews_vendor_id_vendors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('author_id', 'subject', 'operator_id', name='uq_reviews_author_operator'),
    sa.UniqueConstraint('author_id', 'subject', 'service_id', name='uq_reviews_author_service'),
    sa.UniqueConstraint('author_id', 'subject', 'trip_id', name='uq_reviews_author_trip'),
    sa.UniqueConstraint('author_id', 'subject', 'vendor_id', name='uq_reviews_author_vendor')
    )
    op.create_index('ix_reviews_created_at', 'reviews', ['created_at'], unique=False)
    op.create_index('ix_reviews_operator_id', 'reviews', ['operator_id'], unique=False)
    op.create_index('ix_reviews_service_id', 'reviews', ['service_id'], unique=False)
    op.create_index('ix_reviews_subject', 'reviews', ['subject'], unique=False)
    op.create_index('ix_reviews_trip_id', 'reviews', ['trip_id'], unique=False)
    op.create_index('ix_reviews_vendor_id', 'reviews', ['vendor_id'], unique=False)
    op.create_table('assist_messages',
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('sender', postgresql.ENUM('traveller', 'coordinator', 'ai', name='assist_sender', create_type=False), nullable=False),
    sa.Column('sender_name', sa.String(length=120), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(sender = 'ai') = (sender_id IS NULL)", name=op.f('ck_assist_messages_ai_messages_have_no_author')),
    sa.CheckConstraint('length(btrim(body)) >= 1', name=op.f('ck_assist_messages_body_not_empty')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_assist_messages_sender_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_id'], ['assist_threads.id'], name=op.f('fk_assist_messages_thread_id_assist_threads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assist_messages'))
    )
    op.create_index('ix_assist_messages_created_at', 'assist_messages', ['created_at'], unique=False)
    op.create_index('ix_assist_messages_thread_id', 'assist_messages', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assist_messages_thread_id', table_name='assist_messages')
    op.drop_index('ix_assist_messages_created_at', table_name='assist_messages')
    op.drop_table('assist_messages')
    op.drop_index('ix_reviews_vendor_id', table_name='reviews')
    op.drop_index('ix_reviews_trip_id', table_name='reviews')
    op.drop_index('ix_reviews_subject', table_name='reviews')
    op.drop_index('ix_reviews_service_id', table_name='reviews')
    op.drop_index('ix_reviews_operator_id', table_name='reviews')
    op.drop_index('ix_reviews_created_at', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_assist_threads_trip_id', table_name='assist_threads')
    op.drop_index('ix_assist_threads_traveller_id', table_name='assist_threads')
    op.drop_index('ix_assist_threads_status', table_name='assist_threads')
    op.drop_index('ix_assist_threads_operator_id', table_name='assist_threads')
    op.drop_index('ix_assist_threads_last_message_at', table_name='assist_threads')
    op.drop_table('assist_threads')
    # ### end Alembic commands ###

    bind = op.get_bind()
    for name in ('review_subject', 'assist_sender', 'assist_thread_status'):
        postgresql.ENUM(name=name).drop(bind, checkfirst=True)

    # The two notification_type values stay: PostgreSQL cannot drop an enum
    # value, and recreating the type would mean rewriting every column that
    # uses it. They are inert without the tables above.
